### ISSUE TITLE
How to use API with directive-based approach?

### ISSUE THREAD

**Issue by ameyer-pivotal** [vlio20/angular-datepicker#160]
Using something like
```
<input [(ngModel)]="selectedDate" [dpDayPicker]="datePickerConfig" />
```

how would one use the `open()`/`close()` APIs? Also, a `toggle()` would be convenient.

**Comment by vlio20** [comment]
please see in the documentation how to implement the API. You can also check the demo. Regarding the toggle please submit a feature request.

**Comment by menehune23** [comment]
Hang on though. I would not have asked the question without reading your documentation. The problem is that for a directive-based approach, it's not apparent how to get a reference to the day-picker, as the input itself cannot be used (since obviously it has no `.api`).

I really think a second example in your docs for the directive-based approach would be beneficial.

**Comment by menehune23** [comment]
Also as for the demo, how can we see the code for the demo? I must have missed a link to it somewhere.

**Comment by menehune23** [comment]
(Sorry, I'm on a different account, but it's still me)

**Comment by vlio20** [comment]
@menehune23, it is part of this repository, look for the `demo.component.ts` and `demo.component.html`
