### ISSUE TITLE
dp-date-picker always opens current year/month in pop up view on default open

### ISSUE THREAD

**Issue by nareshurs** [vlio20/angular-datepicker#173]
I am trying to show some default month and year to user with dp-date-picker. When user tries to edit, opened datepicker always shows current year even if default value has any one of the previous years.

Is there a way to fix this. I did not find a way in configuration options.

ex: default value is Aug,2015. When I open date picker it shows current month and year instead of displaying 2015 with Aug month

**Comment by vlio20** [comment]
So, what you asking, is to add a capability to open the calendar on specific date - right?

**Comment by jalberto-ghub** [comment]
I am trying to use the date-picker on a (Add/Update) form and would like the date-picker start on the current value (current Moment value on the ngModel). The initial value gets displayed on the form, but the date-picker opens on "now" no mater what. That seems strange if not wrong. Actually the more I think of it the more it looks like a bug.

**Comment by nareshurs** [comment]
Yes. There should be a way to open initial date picket as per default value. We need capability to open based on a specific date

**Comment by jalberto-ghub** [comment]
One more thing about this issue, The problem is in particular annoying when you have set min/max values for the date and today is outside the range. Think of a date restriction of 18 or older. So max=moment().substract(18, 'years')

in this case the user will see unselectable dates for the last 18 years. It would make more sense to instantiate the calendar where values are valid.

**Comment by vlio20** [comment]
please use `displayDate` it should handle exactly your case, it wasn't documented but no it is.

**Comment by vlio20** [comment]
I don't think I understood, could elaborate please?

**Comment by jalberto-ghub** [comment]
You know the little round icon on the text field that you can click on. It takes the calendar to display "today". But if you have set min/max in config so that "today" is out of range and you are on a valid date, you will not have arrow controls allowing you to move towards "today", but you can still do it by clicking on the button. It seems to me that is not the right behaviour, it should be either disabled, or only move so far as the min/max permits, or go to the value of displayDate. On the picture below, i have displayDate set to config.max (=== now() - 18 years). 


![image](https://user-images.githubusercontent.com/13122536/30243467-0a4a5fee-95a2-11e7-9561-f1656081ff52.png)

**Comment by vlio20** [comment]
please open a different issue

**Comment by jalberto-ghub** [comment]
See https://github.com/vlio20/angular-datepicker/issues/189
