### ISSUE TITLE
Carret moved to end of input when date is invalid

### ISSUE THREAD

**Issue by fbeauche** [vlio20/angular-datepicker#297]
With the day picker directive ( and day time picker directive ), the carret is moved to the end of the input when the date is invalid. 

This does not happens with the components.

See this screencast : 
![daypickerbug](https://user-images.githubusercontent.com/9794183/32907960-05b6c4e6-cad0-11e7-8c9c-371dc99d21cb.gif)

- [x] Provide a **minimal code snippet**, please make sure it is well formatted.
tested on the demo page
- [x] Provide a **stackblitz** demo / [stackblitz](https://stackblitz.com/) example that reproduces the bug.
tested on the demo page
- [x] Provide **screenshots** where appropriate
See attached gif
- [x] What's the **version** of Angular you're using?
tested on the demo page
- [x] Does this occur on specific browser?
Tested on chrome, edge and IE

**Comment by pklein** [comment]
After experiencing this issue as well, I had a quick look at the code and suspect this issue is occurring due to [date-picker.directive.ts:184](https://github.com/vlio20/angular-datepicker/blob/2.6.1/src/app/date-picker/date-picker.directive.ts#L184) and [date-picker.directive.ts:200](https://github.com/vlio20/angular-datepicker/blob/2.6.1/src/app/date-picker/date-picker.directive.ts#L200).

It appears that the form control is being updated all the time, which pushes the cursor to the end?

I get why this is happening when the user selects a date from the picker, but when they're typing via the input box, we probably don't need to update the input box again (it _should_ already have the value).

**Comment by vlio20** [comment]
@pklein, good point. Do you want to submit a PR?

**Comment by vlio20** [comment]
resolved in c96f2a2

**Comment by WaterBleu** [comment]
@vlio20 is this the same reason why attempting to type in the date would flicker?

**Comment by vlio20** [comment]
Might be.
