### ISSUE TITLE
Unable to update the min date & min time when there is a inter-dependent date picker components

### ISSUE THREAD

**Issue by iamramkey** [vlio20/angular-datepicker#408]
Hi All,

I have used ng2-date-picker daytime component in my application where I have 2 dates which are from & to. I have used daytime picker in Angular reactive forms.

Mandatory thing is like To must always be greater than from. So, I used config property min-date & minTime in fromDate for current date & next hour, for toDate I have given the value of from date as min date & minTime. For the first time, it is working fine but afterwards irrespective of changes in fromDate toDate is always stays same according to the first selection.

I tried to provide a stakcblitz but after trying for a lot of ways to resolve moment is not a function issue, So, not able to provide the link here.

Reproducible steps: 
When you change the min date of toDate the toDate calendar is not going to update with the updated minDate (only after the first time). That means you cannot select the updated fromDate (minimum date) in the toDate calendar. I have used the daytime calendar in my application.

Usage Syntax :

<dp-date-picker formControlName="{{eachSchedule.formControlName}}" mode="daytime"  [required]="true" [placeholder]="eachSchedule.placeholder" [config]="getCalendarConfig(eachSchedule.formControlName)" theme="dp-material dp-main">
                    </dp-date-picker>

environment details : 
Angular 2 version : 5.2.9
ng2-date-picker version : ^2.6.2
angular2-moment : ^1.8.0

Thanks in advance

**Comment by Maxsky5** [comment]
Hello,

I was facing the same issue.
First, you should use an object instead of a function here `[config]="getCalendarConfig(eachSchedule.formControlName)"` so angular can detect when changes are made on the config object. You will need one config object by component. 

Then when the value from a component changes, you update the fields from the other component's config object : 
`this.firstComponentConfig.max = this.secondComponentDate;`
The problem here is that angular won't trigger the change detection.

You can do `this.config = { ...this.config };` as a workaround.

Maxime

**Comment by vlio20** [comment]
@Maxsky5, it's not a workaround - it's how it is suppose to work :)
Thanks for the explanation.

**Comment by iamramkey** [comment]
Hi @Maxsky5 ,

Thanks for your information.

@vlio20 : I have used ag-grid in my application & they provided me a property called rowData in gridConfig. Whenver I update rowData the grid is being re-populated with new data.

Just for reference : https://www.ag-grid.com/example.php

Update the dropdown in the top with label : Data Size the grid is going to update automatically.

Can you please explain me how to achieve this with date-picker

I dont understand why the same applies to this date-picker.

Thanks
