### ISSUE TITLE
Can't set time of time picker with API moveCalenderTo()

### ISSUE THREAD

**Issue by carlonoelle** [vlio20/angular-datepicker#444]
I want to set the time of the time-picker to be a specific time, in my case the current time rounded to the nearest 15 min in an hour.

I subscribed to the open event of the picker, and on open call moveCalenderTo() with the manipulated current time.

Stackblitz: https://stackblitz.com/edit/angular-k6abay

But it does nothing.
I think waiting for the open event isn't necessary but i kept it in to be sure.

Angular: 7.2.0

**Comment by vlio20** [comment]
Thanks, I will check this out.

**Comment by vlio20** [comment]
Check this one:
https://stackblitz.com/edit/angular-7q6udu?file=src%2Fapp%2Fapp.component.html

moveCalendarTo is just moving the calendar to a specific date (which shouldn't work on a time picker). I have added an `[ngModel]="date"` and updating the date on opening instead of using moveCalendarTo method.

**Comment by carlonoelle** [comment]
Perfect, thank you very much!
That's the solution I am looking for.

**Comment by vlio20** [comment]
Your ⭐️ would be much appreciated

**Comment by carlonoelle** [comment]
Of course, you got it
