### ISSUE TITLE
How do I know about changes?

### ISSUE THREAD

**Issue by arusak** [vlio20/angular-datepicker#77]
Hello! Awesome component, trying to use it, but I have a problem. I need to refresh data on page whenever a user picks a date. However I could not find a way to catch a click or a change event. An \@Output would be nice.

[Documentation in NPM](https://www.npmjs.com/package/ng2-date-picker) seems outdated but it mentions a few outputs. No traces of them in current DatePickerComponent though.

**Comment by vlio20** [comment]
This component is using `ngModel`, see below:   
`<dp-date-picker [(ngModel)]="selectedDate" [config]="datePickerConfig"></dp-date-picker>`
In order to get the selected value you could just use the `(ngModelChange)` hook.

`<dp-date-picker [(ngModel)]="selectedDate" [config]="datePickerConfig" (ngModelChange)="doYourThing()"></dp-date-picker>`

Does it helps?

**Comment by arusak** [comment]
Thank you for pointing at ngModelChange! Works like a charm.

**Comment by vlio20** [comment]
I am glad it helped! 
would be nice if you could give this lib a ⭐️

**Comment by carlhussey** [comment]
How can this be done when used as a directive? 

I have my input like so : `<input type="text" class="form-control input-sm" formControlName="effectiveStartDate"
                  (change)="updateStartDate(startDateInput.value)" [dpDayPicker]="datesConfig" #startDateInput theme="dp-material">`

If I rename `change` to `ngModelChange` it breaks everything. Is there another method I can use for this? I perform another function when the date field changes.

**Comment by vlio20** [comment]
You just need to do it the same as it done the component with `(ngModelChange)="doYourThing()"` or with reactive forms.
